/********************************************************************************************
* HashTable.java
* 
* The HashTable class implements a hash table that maps 10-digit IBSN numbers to book names. 
* It has an initial size of 11 and a load factor of 70%. When the load factor is reached, the 
* table is automatically expanded by doubling its capacity using the expandCapacity() method. 
* Collisions are handled using linear probing.
*********************************************************************************************/

public class HashTable 
{
    private String[] isbnKeys;          // Array to store ISBNs (keys)
    private String[] bookNames;         // Array to store book names (values)
    private int numberOfElements;       // Current number of elements in the hash table
    private int capacity;               // Current capacity of the hash table
    private static final double LOAD_FACTOR = 0.70;     // Load factor
    private static final String DELETED_ELEMENT = "DELETED";    // Placeholder to mark deleted elements 

    /* Constructor to initialize the hash table with an initial capacity of 11. */
    public HashTable()
    {
        this.capacity = 11;
        this.isbnKeys = new String[capacity];
        this.bookNames = new String[capacity];
        this.numberOfElements = 0;
    }

    /* Hashing function to generate a hash index by extracting the last three characters of the 
     * ISBN and applying the modulus operator to this number to ensure the index is within
     * bounds of the table. 
     */
    private int hashingFunction(String isbn)
    {
        String lastThreeChars = "";

        if (!isValidISBN(isbn))
        {
            System.out.println("Invalid ISBN format. Hashing unsuccessful. The ISBN must be a 10-digit number.");
            return -1;
        }
        else
        {
            for (int i = isbn.length() - 3; i < isbn.length(); i++)
            {
                lastThreeChars += isbn.charAt(i);
            }

            int lastThreeDigits = Integer.parseInt(lastThreeChars);
            return lastThreeDigits % capacity;
        }
    }

    /* Method to add an ISBN and book name to the hash table. This method automatically expands 
     * the capacity of the hash table if the load factor is reached. */
    public void add(String isbn, String bookName)
    {
        System.out.println("\nAdding ISBN '" + isbn + "' and its associated book '" + bookName + "' to the table...");
        
        if (!isValidISBN(isbn))
        {
            System.out.println("Invalid ISBN. Unable to add book '" + bookName + "' to the table.\n");
            return;
        }

        // If the table has reached the load factor, resize it (double the size).
        if (numberOfElements >= capacity * LOAD_FACTOR)
        {
            System.out.println("The hash table has exceeded its load factor. Expanding capacity and rehashing...");
            expandCapacity();
        }

        // Compute the initial hash index of the new element using the hashing function. 
        int newElementIndex = hashingFunction(isbn);

        /* While loop to find an available slot in the hash table. Continues as long as the hash index
         * of the new element is not null (empty) and not marked as deleted. */
        while (isbnKeys[newElementIndex] != null && !isbnKeys[newElementIndex].equals(DELETED_ELEMENT))
        {
            /* If the ISBN key at the current index equals the ISBN of the new element, 
             * the associated bookname is updated. */
            if (isbnKeys[newElementIndex].equals(isbn))
            {
                System.out.println("The ISBN '" + isbn + "' already exists in the table. Updating its associated bookname...");
                bookNames[newElementIndex] = bookName;
                return;
            }

            System.out.println("Cell " + newElementIndex + " already contains a book. Searching for the next open slot for " + bookName + "...");
            /* If the ISBN of the new element does not match the ISBN at the index generated by 
             * the hashing function, linear probing is used to check the next index. */
            newElementIndex = (newElementIndex + 1) % capacity;
        }

        /* If the index generated by the hashing function is empty (null) or contains a deleted 
         * element, the new ISBN and book name are inserted into that index. */
        isbnKeys[newElementIndex] = isbn;
        bookNames[newElementIndex] = bookName;

        // Increment number of elements to reflect the addition of an element. 
        numberOfElements++;
    }

    /* Doubles the capacity of the hash table and rehashes all existing elements. */
    private void expandCapacity()
    {
        int newCapacity = capacity * 2;
        String[] oldISBNs = isbnKeys;
        String[] oldBookNames = bookNames;

        isbnKeys = new String[newCapacity];
        bookNames = new String[newCapacity];
        capacity = newCapacity;
        
        // Reset number of elements to 0
        numberOfElements = 0;

        // Rehash the old entries into the new table excluding those marked as deleted.
        for (int i = 0; i < oldISBNs.length; i++)
        {
            if (oldISBNs[i] != null && !oldISBNs[i].equals(DELETED_ELEMENT))
            {
                add(oldISBNs[i], oldBookNames[i]);
            }
        }
    }

    /* Method to find the book name associated with the specified ISBN. Searches for
     * the specified ISBN in the hash table and returns the book name found at that 
     * index. */
    public String find(String isbn)
    {
        int currentIndex = hashingFunction(isbn);
        int startIndex = currentIndex;

        while (isbnKeys[currentIndex] != null)
        {
            /* If the ISBN at the current index matches the specified ISBN, the
             * corresponding book name is returned. The search is successful and
             * the function exits here. */
            if (isbnKeys[currentIndex].equals(isbn))
            {
                return bookNames[currentIndex];
            }

            /* If the ISBN at the current index does not match the specified ISBN, 
             * linear probing is used to check the next index. This allows the method
             * to search the next slot in the array in case a collision occured at the
             * original index, causing the specified ISBN to be moved to a different
             * index.*/
            currentIndex = (currentIndex + 1) % capacity;

            /* If the current index reaches the starting index, it means we have gone through
             * the whole hash table and checked all slots without finding the specified
             * ISBN. In this case, the method returns null to indicate that the book with the 
             * specified ISBN does not exist in the hash table. */
            if (currentIndex == startIndex)
            {
                break;  // Exit the loop once the entire table has been searched. 
            }
        }

        return null;    // Return null if the ISBN is not found. 
    }

    /* Method to remove an ISBN and its associated book name from the hash table. This
     * method does not actually clear the cell containing the specified ISBN, but marks 
     * it as deleted to preserve the probing sequence. This ensures that operations that
     * rely on linear probing still work after elements have been deleted. */
    public void remove(String isbn)
    {
        // Calculates the hash index for the specified ISBN and stores it in currentIndex.
        int currentIndex = hashingFunction(isbn);

        // Start at the generated hash index.
        int startIndex = currentIndex;

        System.out.println("Removing ISBN '" + isbn + "' and its associated book from the table...");

        /* Loop to search for an empty cell in the hash table. */
        while (isbnKeys[currentIndex] != null)
        {
            /* If the ISBN at the current index is equal to the specified ISBN, mark the cell
             * as deleted and set the associated book name to null. */
            if (isbnKeys[currentIndex].equals(isbn))
            {
                System.out.println("The ISBN '" + isbn + "' and its associated book '" + bookNames[currentIndex] + "' was successfully removed from the table.\n");
                isbnKeys[currentIndex] = DELETED_ELEMENT;
                bookNames[currentIndex] = null;

                // Decrement numberOfElements to reflect the removal of an element. 
                numberOfElements--;

                return;
            }

            /* If the ISBN at the current index is not equal to the specified ISBN, move to the 
             * next slot using linear probing. */
            currentIndex = (currentIndex + 1) % capacity;
            
            /* If the loop returns to the starting index without finding a match, the specified 
             * ISBN is not present in the table. Display a message to the user notifying them
             * that the removal was unsuccessful. */
            if (currentIndex == startIndex)
            {
                break;
            }
        }

        System.out.println("The specified ISBN was not found in the hash table.");
    }

    /* Returns true if the ISBN is exactly 10 digits long and false otherwise. */
    public boolean isValidISBN(String isbn)
    {
        if (isbn == null || isbn.length() != 10)
        {
            return false;
        }

        for (int i = 0; i < isbn.length(); i++)
        {
            if (!Character.isDigit(isbn.charAt(i)))
            {
                return false;
            }
        }

        return true;
    }

    /* Returns a string representation of the hash table. */
    @Override
    public String toString()
    {
        String result = "";

        for (int i = 0; i < capacity; i++)
        {
            result += String.format("%2d: ", i);

            if (isbnKeys[i] == null || isbnKeys[i].equals(DELETED_ELEMENT))
            {
                result += "\n";
            }
            else 
            {
                result += isbnKeys[i] + " --> " + bookNames[i] + "\n";
            }
        }

        return result;
    }    
}
